index:
  path:     /
  defaults: { _controller: app.controller.index }
  methods:  [GET]

savings_post:
  path:     /savings
  defaults: { _controller: app.controller.savings.post }
  methods:  [POST]

savings_get_total_balance:
  path:     /savings/total
  defaults: { _controller: app.controller.savings.get_total_balance }
  methods:  [GET]

savings_get_history:
  path:     /savings/history
  defaults: { _controller: app.controller.savings.get_history }
  methods:  [GET]
